name: Deploy Sniper Agent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        # Configuration SSH pour éviter les problèmes d'empreinte
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 31.97.193.13 >> ~/.ssh/known_hosts

        # Déploiement via rsync
        rsync -avz --delete --exclude 'venv/' --exclude 'node_modules/' --exclude '.git/' ./ root@31.97.193.13:/home/ubuntu/blaxing_agents/sniper-per-backend-pro-v2/

        # Redémarrage du service systemd
        ssh root@31.97.193.13 "
          cd /home/ubuntu/blaxing_agents/sniper-per-backend-pro-v2/backend
          # Réinstallation des dépendances si requirements.txt a changé
          if [ -f requirements.txt ]; then
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
          fi
          # Redémarrage du service
          sudo systemctl restart sniper-agent.service
          sudo systemctl status sniper-agent.service
        "
